spring:
  # 测试的时候可以不用mysql
  datasource:
    url: jdbc:mysql://47.93.234.101:3306/jpa_demo?serverTimezone=GMT%2B8&u seUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
